# 數據源配置
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: none # create create-drop update none(default)
        properties:
            hibernate:
                show-sql: true
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                cache:
                    use_second_level_cache: false
                    use_query_cache: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主庫數據源
            master:
                url: jdbc:mysql://localhost:3306/eipulsedemo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Taipei
                username: YenYasir
                password: dd60605
            # 從庫數據源
            slave:
                # 從數據源開關/默認關閉
                enabled: false
                url: 
                username: 
                password: 
            # 初始連接數
            initialSize: 5
            # 最小連接池數量
            minIdle: 10
            # 最大連接池數量
            maxActive: 20
            # 配置獲取連接等待超時的時間
            maxWait: 6000
            # 配置間隔多久才進行一次檢測，檢測需要關閉的空閑連接，單位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一個連接在池中最小生存的時間，單位是毫秒
            minEvictableIdleTimeMillis: 30000
            # 配置一個連接在池中最大生存的時間，單位是毫秒
            maxEvictableIdleTimeMillis: 90000
            # 配置檢測連接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 設置白名單，不填則允許所有訪問
                allow:
                url-pattern: /druid/*
                # 控制台管理用戶名和密碼
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL記錄
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
